
version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo "no"
  pre_build:
    commands:
      - echo si
  build:
    commands:
      - echo nel
  post_build:
    commands:
      - echo "soy un payaso"
artifacts:
  files:
    - template.yaml
  name: upbCodepipeline