AWSTemplateFormatVersion : '2010-09-09'
Transform:
  - AWS::Serverless-2016-10-31

Description: My Lambda Resources
Resources:
  GetMovie:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getMovie
      Environment: 
        Variables:
         USERS_TABLE: !Ref MoviesTable
      Handler: movies.getMovie
      Runtime: python3.6
      CodeUri: package/
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref MoviesTable
      Events:
        GetMovie:
          Type: Api
          Properties:
            RestApiId: !Ref MyAPI
            Path: "/movie/{movieId}"
            Method: GET
          

  PutMovie:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: putMovie
      Environment: 
        Variables:
         USERS_TABLE: !Ref MoviesTable
      Handler: movies.putMovie
      Runtime: python3.6
      CodeUri: package/
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref MoviesTable
      Events:
        GetUsers:
          Type: Api
          Properties:
            RestApiId: !Ref MyAPI
            Path: "/movie/{movie_id}"
            Method: PUT