AWSTemplateFormatVersion : '2010-09-09'
Transform:
  - AWS::Serverless-2016-10-31

Description: My Lambda Resources
Resources:
  GetUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getUser2
      Environment:
        Variables:
          USERS_TABLE: !Ref MyUsersTable
      Handler: users.getUser2
      Runtime: python3.6
      CodeUri: package/
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref MyUsersTable
      Events:
        GetUsers:
          Type: Api
          Properties:
            RestApiId: !Ref MyAPI
            Path: "/user/{userId}"
            Method: GET

  PutUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: putUser2
      Environment:
        Variables:
          USERS_TABLE: !Ref MyUsersTable
      Handler: users.putUser2
      Runtime: python3.6
      CodeUri: package/
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref MyUsersTable
      Events:
        GetUsers:
          Type: Api
          Properties:
            RestApiId: !Ref MyAPI
            Path: "/user/{userId}"
            Method: PUT

  MyAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: my-api-gateway
      StageName: prod
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: swagger.yaml

  MyUsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: my-users-app-4
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
          
  TableNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/movies-app/table/name"
      Type: String
      Value: !Ref MyUsersTable
      
  TableArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/movies-app/table/arn"
      Type: String
      Value: !GetAtt MyUsersTable.Arn